config/routes.rb
CbmpathRequisition::Application.routes.draw do

  root :to => 'home#welcome'

  scope 'admin' do
    match '', :to => 'admin/requisition_forms#index'
  end

  devise_for :users
  ActiveAdmin.routes(self)

  resources :users
  resources :requisition_forms, :only => [:show, :new, :create]

  scope 'search' do
    get 'patients' => 'patients#search'
    get 'doctors' => 'doctors#search'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  address                :string(255)
#  cbm_user_identifier    :integer
#  city                   :string(255)
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  id                     :integer          not null, primary key
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string(255)
#  name                   :string(255)
#  practice_name          :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  sign_in_count          :integer          default(0)
#  state                  :string(255)
#  updated_at             :datetime         not null
#  zipcode                :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :practice_name,
                  :address, :city, :state, :zipcode, :cbm_user_identifier

  validates_presence_of :cbm_user_identifier

  has_many :patients
  has_many :doctors
  has_many :requisition_forms

  before_create :use_practice_name

  def use_practice_name
    self.name  = practice_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource
  skip_authorize_resource :only => [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :practice_name
    = f.input :address
    = f.input :city
    = f.input :state
    = f.input :zipcode

  .form-actions
    = f.button :submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  tr
    th
    th
    th
    th

  - @users.each do |user|
    tr
      td = user.email
      td = link_to 'Show', user
      td = link_to 'Edit', edit_user_path(user)
      td = link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
h1 Welcome #{@user.email}

div
  a.button href=new_requisition_form_path(:type => 'general') Create New General Form
  a.button href=new_requisition_form_path(:type => 'gyn') Create New GYN Form
  a.button href=new_requisition_form_path(:type => 'gi') Create New GI Form

br
br

div
  a.button href=requisition_forms_path View Old Forms
  a.button href=patients_path Manage Patient Info