config/routes.rb
CbmpathRequisition::Application.routes.draw do

  root :to => 'home#welcome'

  scope 'admin' do
    match '', :to => 'admin/requisition_forms#index'
  end

  devise_for :users
  ActiveAdmin.routes(self)

  resources :users
  resources :requisition_forms, :only => [:show, :new, :create]

  scope 'search' do
    get 'patients' => 'patients#search'
    get 'doctors' => 'doctors#search'
  end

end

app/controllers/requisition_forms_controller.rb
require 'net/ftp'
require 'double_bag_ftps'

class RequisitionFormsController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource

  # GET /requisition_forms/1
  # GET /requisition_forms/1.json
  def show
    @requisition_form = RequisitionForm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @requisition_form }
      format.pdf do
        render :pdf => "file_name"
      end
    end
  end

  # GET /requisition_forms/new
  # GET /requisition_forms/new.json
  def new
    @requisition_form = RequisitionForm.new(:collection_date => Date.today)
    @requisition_form.patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @requisition_form }
    end
  end

  # GET /requisition_forms/1/edit
  def edit
    @requisition_form = RequisitionForm.find(params[:id])
  end

  # POST /requisition_forms
  # POST /requisition_forms.json
  def create
    # build patient
    unless params[:requisition_form][:patient_attributes][:id].blank?
      @patient = Patient.find(params[:requisition_form][:patient_attributes][:id])
      authorize! :read, @patient
      params[:requisition_form].delete(:patient_attributes)
    end

    @requisition_form = current_user.requisition_forms.new(params[:requisition_form])
    @requisition_form.patient = @patient if defined? @patient

    respond_to do |format|
      if @requisition_form.save

        @requisition_form.send_via_sftp

        format.html { redirect_to @requisition_form, notice: 'Requisition form was successfully created.' }
        format.json { render json: @requisition_form, status: :created, location: @requisition_form }
      else
        format.html { render action: "new" }
        format.json { render json: @requisition_form.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/requisition_forms_helper.rb
module RequisitionFormsHelper
end

app/views/requisition_forms/_form_general_specimens.html.slim
.row
  .small-12.columns
    h4 Biopsy Specimen Source (Please Label Jars A – J with patient’s complete name, DOB and specimen source)
    .row.gen-specimens
      .small-6.columns
        label for="requisition_form[specimens][a]" class="medical-history-field"
          | A.
          input name="requisition_form[specimens][a]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][b]" class="medical-history-field"
          | B.
          input name="requisition_form[specimens][b]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][c]" class="medical-history-field"
          | C.
          input name="requisition_form[specimens][c]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][d]" class="medical-history-field"
          | D.
          input name="requisition_form[specimens][d]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][e]" class="medical-history-field"
          | E.
          input name="requisition_form[specimens][e]" autocomplete="off" class="text-input"  type="text"
      .small-6.columns
        label for="requisition_form[specimens][f]" class="medical-history-field"
          | F.
          input name="requisition_form[specimens][f]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][g]" class="medical-history-field"
          | G.
          input name="requisition_form[specimens][g]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][h]" class="medical-history-field"
          | H.
          input name="requisition_form[specimens][h]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][i]" class="medical-history-field"
          | I.
          input name="requisition_form[specimens][i]" autocomplete="off" class="text-input"  type="text"
        label for="requisition_form[specimens][j]" class="medical-history-field"
          | J.
          input name="requisition_form[specimens][j]" autocomplete="off" class="text-input"  type="text"

app/views/requisition_forms/_form_gi_medical_history.html.slim
.row
  .small-12.columns.medical-history
    h4 Medical History
    .row
      .small-5.columns
        label for="requisition_form[medical_history][abdominal_pain][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][abdominal_pain][checked]" value="true" autocomplete="off"  Abdominal / Epigastric pain / Other (location: &nbsp;
          span.optional
            input name="requisition_form[medical_history][abdominal_pain][location]" autocomplete="off" disabled="disabled" class="text-input"  type="text"
          |)

        label for="requisition_form[medical_history][anal_lesion][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][anal_lesion][checked]" value="true" autocomplete="off" Anal Lesion

        label for="requisition_form[medical_history][anemia][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][anemia][checked]" value="true" autocomplete="off" Anemia

        label for="requisition_form[medical_history][barretts][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][barretts][checked]" value="true" autocomplete="off" Barrett's

        label for="requisition_form[medical_history][bleeding][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][bleeding][checked]" value="true" autocomplete="off" Bleeding
          span.optional
            input name="requisition_form[medical_history][bleeding][type]" autocomplete="off" type="radio" disabled="disabled" value="Rectal" Rectal
            input name="requisition_form[medical_history][bleeding][type]" autocomplete="off" type="radio" disabled="disabled" value="GI" GI
            input name="requisition_form[medical_history][bleeding][type]" autocomplete="off" type="radio" disabled="disabled" value="Blood in stool" Blood in stool

        label for="requisition_form[medical_history][cancer][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][cancer][checked]" value="true" autocomplete="off" Cancer
          span.optional
            input name="requisition_form[medical_history][cancer][personal]" class="cancer-check" autocomplete="off" type="checkbox" disabled="disabled" value="true" Personal, type: &nbsp;
            span.optional
              input name="requisition_form[medical_history][cancer][personal_type]" class="med-check" autocomplete="off" disabled="disabled" class="text-input" type="text"
            br
            input name="requisition_form[medical_history][cancer][family]" class="cancer-check family-type" autocomplete="off" type="checkbox" disabled="disabled" value="true" Family, type: &nbsp;
            span.optional
              input name="requisition_form[medical_history][cancer][family_type]" autocomplete="off" disabled="disabled" class="text-input" type="text"

        label for="requisition_form[medical_history][colitis][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][colitis][checked]" value="true" autocomplete="off" Colitis
          span.optional
            input name="requisition_form[medical_history][colitis][type]" autocomplete="off" type="radio" disabled="disabled" value="Crohn's" Crohn's
            input name="requisition_form[medical_history][colitis][type]" autocomplete="off" type="radio" disabled="disabled" value="UC" UC
            input name="requisition_form[medical_history][colitis][type]" autocomplete="off" type="radio" disabled="disabled" value="IBD" IBD
            input name="requisition_form[medical_history][colitis][type]" autocomplete="off" type="radio" disabled="disabled" value="Other:" class="cancer-check" Other: &nbsp;
            span.optional
              input name="requisition_form[medical_history][colitis][other]" autocomplete="off" disabled="disabled" class="text-input" type="text"

        label for="requisition_form[medical_history][condyloma][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][condyloma][checked]" value="true" autocomplete="off" Condyloma

        label for="requisition_form[medical_history][constipation][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][constipation][checked]" value="true" autocomplete="off" Constipation

        label for="requisition_form[medical_history][diarrhea_bloody][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][diarrhea_bloody][checked]" value="true" autocomplete="off" Diarrhea,bloody
          input type="checkbox" class="med-check" name="requisition_form[medical_history][diarrhea_watery][checked]" value="true" autocomplete="off" Diarrhea,watery

        label for="requisition_form[medical_history][diverticulosis][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][diverticulosis][checked]" value="true" autocomplete="off" Diverticulosis

      .small-3.columns
        label for="requisition_form[medical_history][dysphagia][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][dysphagia][checked]" value="true" autocomplete="off" Dysphagia

        label for="requisition_form[medical_history][fistula_tract][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][fistula_tract][checked]" value="true" autocomplete="off" Fistula Tract

        label for="requisition_form[medical_history][fungi][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][fungi][checked]" value="true" autocomplete="off" Fungi(Candida)

        label for="requisition_form[medical_history][gastritis][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][gastritis][checked]" value="true" autocomplete="off" Gastritis

        label for="requisition_form[medical_history][gred][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][gred][checked]" value="true" autocomplete="off" GRED(Reflux)

        label for="requisition_form[medical_history][heartburn][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][heartburn][checked]" value="true" autocomplete="off" Heartburn

        label for="requisition_form[medical_history][hemorrhoid][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][hemorrhoid][checked]" value="true" autocomplete="off" Hemorrhoid

        label for="requisition_form[medical_history][history][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][history][checked]" value="true" autocomplete="off" History of &nbsp;
          span.optional
            input name="requisition_form[medical_history][history][history]" autocomplete="off" disabled="disabled" class="text-input" type="text"

        label for="requisition_form[medical_history][lymphoma][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][lymphoma][checked]" value="true" autocomplete="off" Lymphoma

        label for="requisition_form[medical_history][malabsorption][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][malabsorption][checked]" value="true" autocomplete="off" Malabsorption

        label for="requisition_form[medical_history][nausea][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][nausea][checked]" value="true" autocomplete="off" Nausea/ Vomiting

        label for="requisition_form[medical_history][pilonidal_cyst][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][pilonidal_cyst][checked]" value="true" autocomplete="off" Pilonidal Cyst

      .small-4.columns
        label for="requisition_form[medical_history][polyp_site][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][polyp_site][checked]" value="true" autocomplete="off" Polyp site: &nbsp;
          span.optional
            input name="requisition_form[medical_history][polyp_site][polyp_site]" autocomplete="off" disabled="disabled" class="text-input" type="text"

        label for="requisition_form[medical_history][screening_for][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][screening_for][checked]" value="true" autocomplete="off" Screening for: &nbsp;
          span.optional
            input name="requisition_form[medical_history][screening_for][screening_for]" autocomplete="off" disabled="disabled" class="text-input" type="text"

        label for="requisition_form[medical_history][skin_tag][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][skin_tag][checked]" value="true" autocomplete="off" Skin Tag

        label for="requisition_form[medical_history][weight_loss][checked]" class="medical-history-field"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][weight_loss][checked]" value="true" autocomplete="off" Weight Loss

        label for="requisition_form[medical_history][other][checked]" class="medical-history-field other"
          input type="checkbox" class="med-check" name="requisition_form[medical_history][other][checked]" value="true" autocomplete="off" OTHER: &nbsp;
          span.optional
            input name="requisition_form[medical_history][other][other]" autocomplete="off" disabled="disabled" class="text-input" type="text"

        label for="requisition_form[medical_history][rule_out][checked]" class="medical-history-field"
          input type="checkbox" class="rule-out-check" name="requisition_form[medical_history][rule_out][checked]" value="true" autocomplete="off" RULE OUT:
          .row.rule-out
            .optional.small-6.columns
              label for="requisition_form[medical_history][rule_out][barrets][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][barrets][checked]" value="true" autocomplete="off" disabled="disabled" BARRET'S

              label for="requisition_form[medical_history][carcinoma][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][carcinoma][checked]" value="true" autocomplete="off" disabled="disabled" CARCINOMA

              label for="requisition_form[medical_history][rule_out][celiac][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][celiac][checked]" value="true" autocomplete="off" disabled="disabled" CELIAC

              label for="requisition_form[medical_history][rule_out][h_pylori][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][h_pylori][checked]" value="true" autocomplete="off" disabled="disabled" H. PYLORI

            .optional.small-6.columns
              label for="requisition_form[medical_history][rule_out][dysplasia][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][dysplasia][checked]" value="true" autocomplete="off" disabled="disabled" DYSPLASIA

              label for="requisition_form[medical_history][rule_out][esophagitis][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][esophagitis][checked]" value="true" autocomplete="off" disabled="disabled" ESOPHAGITIS

              label for="requisition_form[medical_history][rule_out][giardia][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][giardia][checked]" value="true" autocomplete="off" disabled="disabled" GIARDIA

              label for="requisition_form[medical_history][rule_out][colitis][checked]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][colitis][checked]" value="true" autocomplete="off" disabled="disabled" COLITIS

            .optional.small-12.columns
              label for="requisition_form[medical_history][rule_out][other]" class="medical-history-field"
                input type="checkbox" class="med-check" name="requisition_form[medical_history][rule_out][other][checked]" value="true" autocomplete="off" disabled="disabled" OTHER: &nbsp;
                span.optional
                  input name="requisition_form[medical_history][rule_out][other_text]" autocomplete="off" disabled="disabled" class="text-input" type="text"

app/views/requisition_forms/_form_gi_specimen_row.html.slim
tr.specimen-grid-row.copy-me
  td.bb.br.specimen-first
    span 1
    input type="text" name="requisition_form[specimens][#{Time.now.to_i}][source]" disabled="disabled"
  td.bb.specimen-box
    input type="radio" value="biopsy" name="requisition_form[specimens][#{Time.now.to_i}][type]"
  td.bb.specimen-box
    input type="radio" value="cytology" name="requisition_form[specimens][#{Time.now.to_i}][type]"
  td.bb.specimen-box
    input type="radio" value="polyp" name="requisition_form[specimens][#{Time.now.to_i}][type]"
  th.br.bb.specimen-box
    input type="radio" value="random" name="requisition_form[specimens][#{Time.now.to_i}][type]"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][clo_test]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][antrum]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][fundus]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][stomach]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][cardia]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][duod_bulb]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][duodenum]" disabled="disabled"
  th.br.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][dist_duod]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][esophagus]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][upper_esoph]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][middle_esoph]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][lower_esoph]" disabled="disabled"
  th.br.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][eg_junct]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][ileum]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][ileocecal_valve]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][colon]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][cecum]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][ascending]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][hepatic_flex.]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][transverse]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][splenic_flex]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][descending]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][sigmoid]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][rectosigmoid]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][rectum]" disabled="disabled"
  td.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][right_colon]" disabled="disabled"
  th.br.bb.specimen-box
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][left_colon]" disabled="disabled"
  td.bb.br.specimen-other
    input type="checkbox" value="true" name="requisition_form[specimens][#{Time.now.to_i}][other]" disabled="disabled"
  td.bb
    input type="text" name="requisition_form[specimens][#{Time.now.to_i}][other_blank]" disabled="disabled"

app/views/requisition_forms/_general_specimens.html.slim
div
  b General Specimens

app/views/requisition_forms/_gi_specimen_row.slim
.specimen-row
  b = "#{specimen['source']}: "
  = specimen['type'] == 'biopsy' ? 'Biopsy, ' : ''
  = specimen['type'] == 'cytology' ? 'Cytology, ' : ''
  = specimen['type'] == 'polyp' ? 'Polyp, ' : ''
  = specimen['type'] == 'random' ? 'Random, ' : ''
  = specimen['clo_test'] ? 'CLO Test, ' : ''
  = specimen['antrum'] ? 'Antrum, ' : ''
  = specimen['fundus'] ? 'Fundus, ' : ''
  = specimen['stomach'] ? 'Stomach, ' : ''
  = specimen['cardia'] ? 'Cardia, ' : ''
  = specimen['duod_bulb'] ? 'Duod. Bulb, ' : ''
  = specimen['duodenum'] ? 'Duodenum, ' : ''
  = specimen['dist_duod'] ? 'Dist. Duod, ' : ''
  = specimen['esophagus'] ? 'Esophagus, ' : ''
  = specimen['upper_esoph'] ? 'Upper Esoph., ' : ''
  = specimen['middle_esoph'] ? 'Middle Esoph., ' : ''
  = specimen['lower_esoph'] ? 'Lower Esoph., ' : ''
  = specimen['eg_junct'] ? 'E.G. Junct., ' : ''
  = specimen['ileum'] ? 'Ileum, ' : ''
  = specimen['ileocecal_valve'] ? 'Ileocecal Valve, ' : ''
  = specimen['colon'] ? 'Colon, ' : ''
  = specimen['cecum'] ? 'Cecum, ' : ''
  = specimen['ascending'] ? 'Ascending, ' : ''
  = specimen['hepatic_flex.'] ? 'Hepatic Flex, ' : ''
  = specimen['transverse'] ? 'Transverse, ' : ''
  = specimen['splenic_flex'] ? 'Splenic Flex., ' : ''
  = specimen['descending'] ? 'Descending, ' : ''
  = specimen['sigmoid'] ? 'Sigmoid, ' : ''
  = specimen['rectosigmoid'] ? 'Rectosigmoid, ' : ''
  = specimen['rectum'] ? 'Rectum, ' : ''
  = specimen['right_colon'] ? 'Right Colon, ' : ''
  = specimen['left_colon'] ? 'Left Colon, ' : ''
  = specimen['other'] ? "Other: #{specimen['other_blank']}" : ''

app/views/requisition_forms/_gyn_laboratory_tests.html.slim
div
  b Laboratory Tests...

app/views/requisition_forms/_show_general_medical_history.slim
div
  = @requisition_form.medical_history['text']

app/views/requisition_forms/_show_gi_specimens.html.slim
.row
  .small-12.columns.specimens.bl.br.bt
    table cellspacing=0 cellpadding=0
      tr
        th.br.bb colspan=1
          .head Specimen Source
        th.br.bb colspan=4
          .head Type
          .content check only one
        th.br.bb colspan=13
          .head Upper GI
          .content
            .align-left stomach/duodenum
            .align-right esophagus
        th.br.bb colspan=14
          .head Lower GI
        th.bb colspan=2
          .head Endoscopic Findings
      tr.specimen-headers
        th.br.bb
        th.bb
          .vertical-text Biopsy
        th.bb
          .vertical-text Cytology
        th.bb
          .vertical-text Polyp
        th.br.bb
          .vertical-text Random
        th.bb
          .vertical-text CLO Test
        th.bb
          .vertical-text Antrum
        th.bb
          .vertical-text Fundus
        th.bb
          .vertical-text Stomach
        th.bb
          .vertical-text Cardia
        th.bb
          .vertical-text Duod. Bulb
        th.bb
          .vertical-text Duodenum
        th.br.bb
          .vertical-text Dist. Duod
        th.bb
          .vertical-text Esophagus
        th.bb
          .vertical-text Upper Esoph.
        th.bb
          .vertical-text Middle Esoph.
        th.bb
          .vertical-text Lower Esoph.
        th.br.bb
          .vertical-text E.G. Junct.
        th.bb
          .vertical-text Ileum
        th.bb
          .vertical-text Ileocecal Valve
        th.bb
          .vertical-text Colon
        th.bb
          .vertical-text Cecum
        th.bb
          .vertical-text Ascending
        th.bb
          .vertical-text Hepatic Flex.
        th.bb
          .vertical-text Transverse
        th.bb
          .vertical-text Splenic Flex
        th.bb
          .vertical-text Descending
        th.bb
          .vertical-text Sigmoid
        th.bb
          .vertical-text Rectosigmoid
        th.bb
          .vertical-text Rectum
        th.bb
          .vertical-text Right Colon
        th.br.bb
          .vertical-text Left Colon
        th.br.bb
          .vertical-text Other
        th.bb
      - @requisition_form.specimens.each_with_index do |specimen, i|
        = render "gi_specimen_row", :specimen => specimen[1], :number => i + 1

app/views/requisition_forms/_show_gyn_laboratory_tests.html.slim
.row
  .small-12.columns.laboratory-tests.ba
    div.head Laboratory Tests
    .row
      .small-4.columns
        .input
          .box = @requisition_form.medical_history['high'] ? 'X' : ''
          span Pap with High-Risk HPV;
        .input
          .box = @requisition_form.medical_history['high_16'] ? 'X' : ''
          span Pap with High-Risk HPV; Reflex 16/18;
      .small-4.columns
        .input
          .box = @requisition_form.medical_history['reflex'] ? 'X' : ''
          span Pap w/reflex to High-Risk HPV;
        .input
          .box = @requisition_form.medical_history['reflex_16'] ? 'X' : ''
          span Pap w/reflex High-Risk HPV; Reflex 16/18;
      .small-4.columns
        .input
          .box = @requisition_form.medical_history['gc'] ? 'X' : ''
          span GC/Chl/Trich;
        .input
          .box = @requisition_form.medical_history['other']['checked'] ? 'X' : ''
          span
            | Other: #{@requisition_form.medical_history['other']['text']}

app/views/requisition_forms/_show_gyn_laboratory_tests.slim
-if @requisition_form.medical_history['high']
  div Pap with High-Risk HPV;
- if @requisition_form.medical_history['high_16']
  div Pap with High-Risk HPV; Reflex 16/18;
-if @requisition_form.medical_history['pap_only']
  div Pap only;
-if @requisition_form.medical_history['reflex']
  div Pap w/reflex to High-Risk HPV;
- if @requisition_form.medical_history['reflex_16']
  div Pap w/reflex High-Risk HPV; Reflex 16/18;
- if @requisition_form.medical_history['gc']
  div GC/Chl/Trich;
- if @requisition_form.medical_history['other']['checked']
  div Other: #{@requisition_form.medical_history['other']['text']}

app/views/requisition_forms/edit.html.slim
h1 Editing requisition_form

== render 'form'

= link_to 'Show', @requisition_form
'|
= link_to 'Back', admin_requisition_forms_path

app/views/requisition_forms/new.html.slim
== render 'form'

= link_to 'Back', admin_requisition_forms_path

app/views/requisition_forms/show.html.slim
p#notice = notice


= link_to 'Edit', edit_requisition_form_path(@requisition_form)
'|
= link_to 'Back', requisition_forms_path