config/routes.rb
CbmpathRequisition::Application.routes.draw do

  root :to => 'home#welcome'

  scope 'admin' do
    match '', :to => 'admin/requisition_forms#index'
  end

  devise_for :users
  ActiveAdmin.routes(self)

  resources :users
  resources :requisition_forms, :only => [:show, :new, :create]

  scope 'search' do
    get 'patients' => 'patients#search'
    get 'doctors' => 'doctors#search'
  end

end

app/views/layouts/application.html.slim
doctype html
== "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->"
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"

head
  meta charset="utf-8"

  / Uncomment to make IE8 render like IE7
  / meta http-equiv="X-UA-Compatible" content="IE=7"

  / Set the viewport width to device width for mobile
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  title= content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag "application", :media => 'all'

  = javascript_include_tag "vendor/custom.modernizr"

  = csrf_meta_tag

body id="#{params[:controller]}-#{params[:action]}" class="active_admin"
  #main-container

    - for name,msg in flash
      div class="alert-box #{name == :notice ? "success" : "alert"}"
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

    - if signed_in?
      #mast-nav
        a.brand href=root_path CBM Pathology
        .right
          = link_to "patients", admin_patients_path
          | &sdot;
          = link_to "forms", admin_requisition_forms_path

    #main-content
      == yield

    = wicked_pdf_javascript_include_tag "application"

app/views/layouts/pdf.html.slim
doctype html

head
  = wicked_pdf_stylesheet_link_tag "application"

body
  == yield